/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#19724f",
        "on-primary-fixed-variant": "#0e5138",
        "surface-container-highest": "#c1ecd4",
        "on-error-container": "#93000a",
        "surface-dim": "#b8e4cc",
        "on-secondary-fixed": "#002113",
        "secondary-container": "#a0f4c8",
        "inverse-primary": "#95d4b3",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#002114",
        "surface": "#e8fff0",
        "error-container": "#ffdad6",
        "on-primary-container": "#a8e7c5",
        "tertiary-fixed-dim": "#ffb780",
        "surface-variant": "#c1ecd4",
        "background": "#e8fff0",
        "outline-variant": "#bfc9c1",
        "primary-fixed": "#b1f0ce",
        "surface-container-low": "#d1fee5",
        "primary-container": "#2d6a4f",
        "on-tertiary-fixed": "#2f1400",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "inverse-on-surface": "#cffbe2",
        "on-secondary-fixed-variant": "#005236",
        "surface-container": "#ccf8df",
        "inverse-surface": "#0e3727",
        "tertiary": "#713900",
        "outline": "#707973",
        "on-secondary": "#ffffff",
        "on-surface": "#002114",
        "on-surface-variant": "#404943",
        "tertiary-fixed": "#ffdcc4",
        "secondary": "#0e6c4a",
        "surface-bright": "#e8fff0",
        "tertiary-container": "#8f4f14",
        "secondary-fixed-dim": "#85d7ad",
        "on-error": "#ffffff",
        "surface-tint": "#2c694e",
        "on-tertiary": "#ffffff",
        "on-background": "#002114",
        "primary": "#0f5238",
        "secondary-fixed": "#a0f4c8",
        "on-tertiary-fixed-variant": "#6f3800",
        "surface-container-high": "#c6f2da",
        "on-tertiary-container": "#ffd1b1",
        "primary-fixed-dim": "#95d4b3",
        "severity-danger": "#E76F51",
        "severity-warning": "#F4A261"
      },
      borderRadius: {
        "DEFAULT": "8px",
        "lg": "8px",
        "xl": "12px",
        "full": "9999px"
      },
      spacing: {
        "margin-tablet": "32px",
        "xs": "4px",
        "lg": "24px",
        "base": "8px",
        "xl": "32px",
        "margin-mobile": "16px",
        "gutter": "16px",
        "md": "16px",
        "sm": "8px"
      },
      fontFamily: {
        body: ["Inter", "sans-serif"],
        bengali: ["Noto Sans Bengali", "sans-serif"]
      }
    },
  },
  plugins: [],
}
